version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.8.3
     working_directory: /go/src/github.com/ernestio/logger
     steps:
       - checkout
       - run: docker build -t testbox .
       - run: docker images
       - run: ls
       - run: docker -v
