version: 2
jobs:
   build:
     docker:
       - image: quay.io/r3labs/circleci:golang1.8.3
         environment:
           NATS_URI:  nats://127.0.0.1:4222
#           ROOTPATH: /home/ubuntu/.go_workspace/src/github.com/ernestio
           NATS_URI_TEST:  nats://127.0.0.1:4222
#           GOBIN: /home/ubuntu/.go_workspace/bin
           CURRENT_INSTANCE: http://ernest.local:80/
           JWT_SECRET: test
           IMPORT_PATH: "github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
           ERNEST_LOG_FILE: '/tmp/ernest.log'
           ERNEST_APPLY_DELAY: 1
           ERNEST_CRYPTO_KEY: mMYlPIvI11z20H1BnBmB223355667788
     working_directory: /go/src/github.com/ernestio/logger
     steps:
       - checkout
       - run: echo 127.0.0.1 ernest.local | sudo tee -a /etc/hosts
       - run: mkdir /home/ubuntu
       - run: make dev-deps
       - run: make lint
       - run: make test
       - run: git clone git@github.com:ernestio/toolset.git /tmp/toolset/
       - run: pwd
       - run: cd /tmp/toolset && bundle install
       - run: pwd
       - run: echo "CIRCLE_WORKING_DIRECTORY = $CIRCLE_WORKING_DIRECTORY"
       - run: echo "GOBIN = $GOBIN"
       - run: ruby /tmp/toolset/ernestci/run.rb .ernest-ci
#       - run: mkdir -p $ROOTPATH/
#       - run: rm -rf $ROOTPATH/logger
#       - run: cp -R /home/ubuntu/logger $ROOTPATH/logger
#       - run: cd $ROOTPATH/logger/ && make dev-deps
#       - run: rm -rf $ROOTPATH/toolset/ && git clone git@github.com:ernestio/toolset.git $ROOTPATH/toolset/
#       - run: cd $ROOTPATH/toolset/ernestci/ && bundle install
#       - run: cd $ROOTPATH/logger/ && make test
#       - run: ruby $ROOTPATH/toolset/ernestci/run.rb .ernest-ci
#       - run: cd $ROOTPATH/logger/ && make lint
