version: 2
jobs:
   build:
     machine:
       image: circleci/classic:201709-01
     environment:
       NATS_URI:  nats://127.0.0.1:4222
       ROOTPATH: /home/ubuntu/.go_workspace/src/github.com/ernestio
       NATS_URI_TEST:  nats://127.0.0.1:4222
       GOBIN: /home/ubuntu/.go_workspace/bin
       CURRENT_INSTANCE: http://ernest.local:80/
       JWT_SECRET: test
       IMPORT_PATH: "github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
       ERNEST_LOG_FILE: '/tmp/ernest.log'
       ERNEST_APPLY_DELAY: 1
       ROOTPATH: /home/ubuntu/.go_workspace/src/github.com/ernestio
       ERNEST_CRYPTO_KEY: mMYlPIvI11z20H1BnBmB223355667788
#     working_directory: /go/src/github.com/ernestio/logger
     steps:
       - checkout

       - run: echo 127.0.0.1 ernest.local | sudo tee -a /etc/hosts
       - run: mkdir -p $ROOTPATH
       - run: rm -rf $ROOTPATH/logger
       - run: cd $ROOTPATH/logger/ && make dev-deps
       - run: rm -rf $ROOTPATH/toolset/ && git clone git@github.com:ernestio/toolset.git $ROOTPATH/toolset/
       - run: cd $ROOTPATH/toolset/ernestci/ && bundle install
       - run: cd $ROOTPATH/logger/ && make test
       - run: ruby $ROOTPATH/toolset/ernestci/run.rb .ernest-ci
       - run: cd $ROOTPATH/logger/ && make lint


#       - setup_remote_docker:
#           version: 17.07.0-ce
#       - run: whoami
#       - run: pwd
#       - run: env
#       - run: docker -v
#       - run: echo $CURRENT_INSTANCE
#       - run: ps -aux
#       - run: 
#           name: hello
#           command: echo hello
#       - run: ls
#           name: ernest
#           command: |
#             docker create --name ernest quay.io/r3labs/circleci:golang1.8.3 /bin/true
#             docker exec ernest mkdir -p /go/src/github.com/ernestio/logger
#             docker cp /go/src/github.com/ernestio/logger ernest:/go/src/github.com/ernestio/logger
#             docker cp $DOCKER_CERT_PATH ernest:$DOCKER_CERT_PATH
#             docker exec ernest echo 127.0.0.1 ernest.local | sudo tee -a /etc/hosts
#             docker exec ernest sudo mkdir /home/ubuntu 
#             docker exec ernest cd /go/src/github.com/ernestio/logger && make dev-deps
             #             docker exec ernest docker -H $DOCKER_HOST --tls --tlscert $DOCKER_CERT_PATH/cert.pem --tlskey $DOCKER_CERT_PATH/key.pem --tlscacert $DOCKER_CERT_PATH/ca.pem run busybox hostname

#       - run: |
#           docker run -d --name ernest quay.io/r3labs/circleci:golang1.8.3 tail -f /dev/null
#           docker cp $DOCKER_CERT_PATH ernest:$DOCKER_CERT_PATH
#           docker exec ernest docker -H $DOCKER_HOST --tls --tlscert $DOCKER_CERT_PATH/cert.pem --tlskey $DOCKER_CERT_PATH/key.pem --tlscacert $DOCKER_CERT_PATH/ca.pem run busybox hostname

#       - run: echo 127.0.0.1 ernest.local | sudo tee -a /etc/hosts
#       - run: sudo mkdir /home/ubuntu
#       - run: make dev-deps
#       - run: make lint
#       - run: env
#       - run: make test
#       - run: git clone -b f-circleci-v2-680 git@github.com:ernestio/toolset.git /tmp/toolset/
#       - run: cd /tmp/toolset/ernestci && bundle install
#       - run: 
#           command: ruby /tmp/toolset/ernestci/run.rb .ernest-ci


#           environment:
#             CIRCLE_WORKING_DIRECTORY: /tmp
#       - run: mkdir -p $ROOTPATH/
#       - run: rm -rf $ROOTPATH/logger
#       - run: cp -R /home/ubuntu/logger $ROOTPATH/logger
#       - run: cd $ROOTPATH/logger/ && make dev-deps
#       - run: rm -rf $ROOTPATH/toolset/ && git clone git@github.com:ernestio/toolset.git $ROOTPATH/toolset/
#       - run: cd $ROOTPATH/toolset/ernestci/ && bundle install
#       - run: cd $ROOTPATH/logger/ && make test
#       - run: ruby $ROOTPATH/toolset/ernestci/run.rb .ernest-ci
#       - run: cd $ROOTPATH/logger/ && make lint
